configuration: 
  name: helloqa
  author: oaqa
  
persistence-provider:
  inherit: helloqa.db.local-persistence-provider

collection-reader:
  inherit: helloqa.collection.decorated-collection-reader
  dataset: GUTENBERG
  file: /input/small.txt
#  inherit: fs.dir-collection-reader
#  dataset: GUTENBERG
#  suffix: txt
#  dir: /input
  
pipeline:
  - inherit: jdbc.sqlite.cse.phase  
    name: keyterm-extractor
    options: |
      - inherit: helloqa.keyterm.simple
  
  - inherit: jdbc.sqlite.cse.phase 
    name: retrieval-strategist
    options: |
      - inherit: helloqa.retrieval.simple-solr-strategist
      
  - inherit: jdbc.sqlite.cse.phase  
    name: passage-extractor
    options: |
      - inherit: helloqa.passage.simple

  - inherit: jdbc.eval.retrieval-aggregator-consumer
  
  - inherit: helloqa.eval.passage-map-aggregator-consumer

post-process: 
  - inherit: jdbc.eval.retrieval-evaluator-consumer
  - inherit: report.csv-report-generator
    builders: |
      - inherit: jdbc.report.f-measure-report-component
      
  - inherit: helloqa.eval.passage-map-evaluator-consumer
  - inherit: report.csv-report-generator
    builders: |
      - inherit: helloqa.report.map-report-component
  